### ISSUE TITLE
Request for Chinese language support

### ISSUE THREAD

**Issue by noock** [SlimRoms/frameworks_base#1]
Hi friends! I'm from China and I do appreciate your ROM very much. It will be better if it supports Chinese. I hope it does in version 2.6. Expecting ....

**Comment by krarvind** [comment]
At this point, i am keeping it to 5 system languages, but there is a chinese text support available via my OTA app/ addons/alllanguagefonts.zip. That should enable reading chinese fonts in text.

**Comment by noock** [comment]
I set system language to English. With Chinese fonts, the text display well. But the system language is set to other language, So many application use English as UI language. e.g. Google maps, the place are shown in English, that's no so good.

**Comment by krarvind** [comment]
well as i said, its 5 languages for now. Feel free to compile from my source though for your language or it will have to be a customized (paid) project ( contact via my website, contact form)
